modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/lukebemish/excavated_variants/issues"
license = "LGPL v3"

[[mods]]
modId = "excavated_variants"
version = "${version}"
displayName = "Excavated Variants"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.excavated_variants]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.excavated_variants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.excavated_variants]]
modId = "architectury"
mandatory = true
versionRange = "[3.4.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.excavated_variants]]
modId = "dynamic_asset_generator"
mandatory = true
versionRange = "[0.5.0,)"
ordering = "AFTER"
side = "BOTH"