modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/lukebemish/excavated_variants/issues"
license = "LGPL v3"

[[mods]]
modId = "excavated_variants"
version = "${file.jarVersion}"
displayName = "Excavated Variants"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.excavated_variants]]
modId = "forge"
mandatory = true
versionRange = "[41.0.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.excavated_variants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.excavated_variants]]
modId = "dynamic_asset_generator"
mandatory = true
versionRange = "[0.6.3,)"
ordering = "AFTER"
side = "BOTH"