name: Mod Compatibility Request
description: Request compatibility for a mod
title: "[MOD COMPAT] Mod compat request..."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        If you want compatibility with another mod, have you first looked into whether you can accomplish your goal through the config system? See the README for details. If you can accomplish this compatibility through a config, feel free to open a pull request to add it as a default config. It should be placed under `common/src/main/resource/default_configs`.
  - type: input
    id: modid
    attributes:
      label: Mod Name
      description: What mod are you looking for compat with?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why can't this be done through a config?
      description: Please give details for what new features or changes to existing features are required to add compatibility.
  - type: textarea
    id: otherinfo
    attributes:
      label: Is there any other relevant info about this issue?
      description: Add any other relevant information here
    validations:
      required: true
